version: '3.8'

services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    working_dir: /app
    command: python webapp/app.py

  cli:
    build: .
    volumes:
      - .:/app
    working_dir: /app
    command: python cli/cli_view.py
